---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /sbin/init

verifier:
  name: inspec

provisioner:
  name: salt_solo
  salt_version: latest
  require_chef: false
  formula: vault

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
  - name: centos-7
    driver_config:
      provision_command:
        - yum -y install net-tools    # needed by inspec
  - name: amazonlinux
    driver_config:
      provision_command:
        - yum install -y epel-release
      image: amazonlinux:1
      platform: rhel

suites:
  - name: dev_server
    provisioner:
      state_top:
        base:
          '*':
            - vault.server
  - name: prod_server
    provisioner:
      state_top:
        base:
          '*':
            - vault.server
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            dev_mode: false
            tls_disable: 1
