---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /sbin/init
  provision_command:
    - curl -L https://bootstrap.saltstack.com | sh -s -- -X

verifier:
  name: inspec

provisioner:
  name: salt_solo
  salt_version: latest
  require_chef: false
  formula: vault

platforms:
  - name: ubuntu-16.04
    driver:
      name: docker
      provision_command:
        - apt-get install -y locales && locale-gen en_US.UTF-8
        - curl -L https://bootstrap.saltstack.com | sh -s -- -X
  - name: centos-7
    driver:
      name: docker
      provision_command:
        - yum -y install net-tools    # needed by inspec
        - curl -L https://bootstrap.saltstack.com | sh -s -- -X
  - name: amazonlinux
    driver:
      name: docker
      image: amazonlinux:1
      platform: rhel

suites:
  - name: dev_server
    provisioner:
      state_top:
        base:
          '*':
            - vault.server
  - name: prod_server
    provisioner:
      state_top:
        base:
          '*':
            - vault.server
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            dev_mode: false
            tls_disable: 1
            self_signed_cert:
              enabled: true
              hostname: localhost
              password: localhost
              country: GB
              state: England
              city: London
              org: example.com
              org_unit: testing
