---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /sbin/init
  provision_command:
    - curl -L https://bootstrap.saltstack.com | sh -s -- -X     # install Salt and dependencies here to make use of Docker build cache, speeding up tests massively

verifier:
  name: inspec

provisioner:
  name: salt_solo
  salt_version: latest
  log_level: info
  require_chef: false
  formula: vault

platforms:
  - name: ubuntu-16.04
    driver:
      name: docker
      provision_command:
        - apt-get install -y locales net-tools && locale-gen en_US.UTF-8
        - curl -L https://bootstrap.saltstack.com | sh -s -- -X
  - name: centos-7
    driver:
      name: docker
      provision_command:
        - yum -y install net-tools    # needed by inspec
        - curl -L https://bootstrap.saltstack.com | sh -s -- -X
  - name: amazonlinux
    driver:
      name: docker
      image: amazonlinux:1
      platform: rhel

suites:
  - name: install_binary
    provisioner:
      state_top:
        base:
          '*':
            - vault
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
#            version: 0.11.1    # test upgrades by doing a double-converge, changing the version pillar between each one
            version: 0.11.2
            secure_download: false

  - name: dev_server
    provisioner:
      state_top:
        base:
          '*':
            - vault
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            dev_mode: True
  - name: prod_server
    provisioner:
      state_top:
        base:
          '*':
            - vault
      pillars:
        top.sls:
          base:
            '*':
              - vault
        vault.sls:
          vault:
            tls_disable: 1
            self_signed_cert:
              enabled: true
              hostname: localhost
              password: localhost
              country: GB
              state: England
              city: London
              org: example.com
              org_unit: testing
