sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: dev
    - INSTANCE: prod

script: bundle exec kitchen test ${INSTANCE}
