sudo: required
language: ruby

services:
  - docker

cache:
  bundler: true

before_install:
  - gem install bundler --no-document

env:
  - PLATFORM=ubuntu
  - PLATFORM=centos
  - PLATFORM=amazon

script: bundle exec kitchen test ${PLATFORM}
